name: muon_p
defaults:
  - lr_config: linear
lr_config:
  lr: 0.05

adam_lr: 0.03

config:
  momentum: 0.95
  nesterov: True
  schatten_p: 2
  ns_steps: 6

  adam_beta1: 0.95
  adam_beta2: 0.95
  adam_eps: 1e-8
  adam_wd: 0.0